import { library, dom, config } from "@fortawesome/fontawesome-svg-core";

config.autoAddCss = false;

import {
  faAnchor as farAnchor,
  faArrowDown as farArrowDown,
  faArrowLeft as farArrowLeft,
  faArrowRight as farArrowRight,
  faArrowRightFromBracket as farArrowRightFromBracket,
  faArrowUp as farArrowUp,
  faArrowUpRightDots as farArrowUpRightDots,
  faArrowUpRightFromSquare as farArrowUpRightFromSquare,
  faBars as farBars,
  faBookmark as farBookmark,
  faCalendar as farCalendar,
  faCalendarLines as farCalendarLines,
  faCalendarLinesPen as farCalendarLinesPen,
  faCheck as farCheck,
  faChevronDown as farChevronDown,
  faChevronLeft as farChevronLeft,
  faChevronRight as farChevronRight,
  faChevronUp as farChevronUp,
  faCircleCheck as farCircleCheck,
  faClock as farClock,
  faEnvelope as farEnvelope,
  faFilePdf as farFilePdf,
  faInfo as farInfo,
  faMagnifyingGlass as farMagnifyingGlass,
  faPencil as farPencil,
  faPlus as farPlus,
  faSliders as farSliders,
  faTick as farTick,
  faTrashXmark as farTrashXmark,
  faXmark as farXmark,
} from "@fortawesome/sharp-regular-svg-icons";

import {
  faBookmark as fasBookmark,
  faCartShopping as fasCartShopping,
  faCalendar as fasCalendar,
  faChevronDown as fasChevronDown,
  faChevronLeft as fasChevronLeft,
  faChevronRight as fasChevronRight,
  faCircleCheck as fasCircleCheck,
  faCircleExclamation as fasCircleExclamation,
  faCirclePause as fasCirclePause,
  faCirclePlay as fasCirclePlay,
  faCircleUser as fasCircleUser,
  faCircleInfo as fasCircleInfo,
  faCircleX as fasCircleX,
  faClock as fasClock,
  faEnvelope as fasEnvelope,
  faExclamationCircle as fasExclamationCircle,
  faEye as fasEye,
  faFileInvoice as fasFileInvoice,
  faFileLines as fasFileLines,
  faKeynote as fasKeynote,
  faLocationDot as fasLocationDot,
  faPhone as fasPhone,
  faPrint as fasPrint,
  faQuestionCircle as fasQuestionCircle,
  faSquareCheck as fasSquareCheck,
  faTriangleExclamation as fasTriangleExclamation,
  faTags as fasTags,
  faUser as fasUser,
  faUserCheck as fasUserCheck,
  faUserTie as fasUserTie,
  faUsersLine as fasUsersLine,
  faXmark as fasXmark,
} from "@fortawesome/sharp-solid-svg-icons";

import {
  faCcAmex,
  faCcMastercard,
  faCcVisa,
  faFacebookF,
  faInstagram,
  faLinkedinIn,
  faThreads,
  faWhatsapp,
  faXTwitter,
  faYoutube,
} from "@fortawesome/free-brands-svg-icons";

export default (function () {
  library.add(
    // Sharp regular style
    farAnchor,
    farArrowDown,
    farArrowLeft,
    farArrowRight,
    farArrowRightFromBracket,
    farArrowUp,
    farArrowUpRightDots,
    farArrowUpRightFromSquare,
    farBars,
    farBookmark,
    farCalendar,
    farCalendarLines,
    farCalendarLinesPen,
    farCheck,
    farChevronDown,
    farChevronLeft,
    farChevronRight,
    farChevronUp,
    farCircleCheck,
    farClock,
    farEnvelope,
    farFilePdf,
    farInfo,
    farMagnifyingGlass,
    farPencil,
    farPlus,
    farSliders,
    farTick,
    farTrashXmark,
    farXmark,

    // Sharp Solid Style
    fasBookmark,
    fasCartShopping,
    fasCalendar,
    fasChevronDown,
    fasChevronLeft,
    fasChevronRight,
    fasCircleCheck,
    fasCircleExclamation,
    fasCircleInfo,
    fasCirclePause,
    fasCirclePlay,
    fasCircleUser,
    fasCircleX,
    fasClock,
    fasEnvelope,
    fasExclamationCircle,
    fasFileInvoice,
    fasFileLines,
    fasEye,
    fasExclamationCircle,
    fasKeynote,
    fasLocationDot,
    fasPhone,
    fasPrint,
    fasQuestionCircle,
    fasSquareCheck,
    fasTags,
    fasTriangleExclamation,
    fasUser,
    fasUserCheck,
    fasUserTie,
    fasUsersLine,
    fasXmark,

    // Brand style
    faCcAmex,
    faCcMastercard,
    faCcVisa,
    faFacebookF,
    faInstagram,
    faLinkedinIn,
    faThreads,
    faWhatsapp,
    faXTwitter,
    faYoutube
  );

  window.addEventListener("DOMContentLoaded", () => {
    config.searchPseudoElements = true;
    dom.i2svg();
    dom.watch();
  });
})();
